# Generated by Django 5.0.6 on 2024-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_wallet_deposit_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='owner',
        ),
    ]
