# Generated by Django 5.0.6 on 2024-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_planes_subscription_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_planes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
