# Generated by Django 5.0.6 on 2024-07-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_admin_user_alter_trainee_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='user',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='user',
            new_name='trainer',
        ),
    ]
